services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - task-manager_logs:/logs
    environment:
      NODE_ENV: production
      LOG_DIR: /logs
    restart: unless-stopped

volumes:
  task-manager_logs:

